### ISSUE TITLE
블록이동 버그

### ISSUE THREAD

**Issue by hyeoneedyou** [CSID-DGU/2021-1-OSSPC-WelcomeOS-1#15]
전: 블록 생성에 지연 발생, 블록이 바닥에 닿아도 일정 시간 이동가능

후: 블록이 바닥에 닿으면 바로 다음 블록 생성

Set speed 부분의 set_timer 수정

**Comment by leechaelim** [comment]
Set speed 부분의 set_timer의 문제가 아니고, 
# Create new mino의 bottom_count가 문제인 걸로 확인했습니다!
bottom_count 크기 조절해서 해결하도록 하겠습니다.
