### ISSUE TITLE
PVP Game over 엔딩화면 버그

### ISSUE THREAD

**Issue by hyeoneedyou** [CSID-DGU/2021-1-OSSPC-WelcomeOS-1#19]
전: 1P, 2P GAMEOVER시 엔딩 화면 무한 반복

후: 1P, 2P GAMEOVER시 win& lose 화면과 `# Game over screen` 보여줌

**Comment by leechaelim** [comment]
오른쪽 창 플레이어가 죽으면 win, lose 잠깐 나왔다가 게임 종료되는데
sleep(몇초)으로 몇 초 멈추게 해주면 혹시 해결 될까 생각이 드네여,,,,,
