### ISSUE TITLE
자동 추천 기능

### ISSUE THREAD

**Issue by hyeoneedyou** [CSID-DGU/2021-1-OSSPC-WelcomeOS-1#36]
1. h버튼을 누르면 자동으로 최적의 위치에 블록을 쌓아준다.
2. 언제, 얼마만큼 자동 추천 기능을 사용할 수 있도록 할 것인지는 더욱 논의가 필요.
3. 클래식 모드에 적용하도록 구현하고, 가능하다면 다른 모드까지 확장한다.

**Comment by leechaelim** [comment]
1. https://github.com/LoveDaisy/tetris_game
2. https://github.com/YangtaoGe518/Tetris-AI( https://github.com/CSID-DGU/2020-2-OSSP-CP--YamiYami_Z_Z-5)
